[tool.poetry]
name = "asteroid_game"
version = "0.1.0"
description = ""
authors = ["eva"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pygame = "2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
